// shop/angular-client/src/app/components/navbar/navbar.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';
import { AccountService } from '../../services/account.service';
import { CartService } from '../../services/cart.service';
import { Photo } from '../../models/photo.model';
import {
  NgbDropdownModule,
  NgbPopoverModule,
  NgbScrollSpyModule,
  NgbScrollSpyService,
} from '@ng-bootstrap/ng-bootstrap';
import { PaginationList } from '../../models/pagination-list.model';
import { NotificationModel } from '../../models/notification.model';
import { NotificationService } from '../../services/notification.service';
import { NotificationCardComponent } from '../notification-card/notification-card.component';
import {
  InfiniteScrollDirective,
  InfiniteScrollModule,
} from 'ngx-infinite-scroll';
import { HasRoleDirective } from '../../directives/has-role.directive';

@Component({
  selector: 'app-navbar',

  standalone: true,
  imports: [
    CommonModule,
    RouterLink,
    NgbDropdownModule,
    NgbPopoverModule,
    NotificationCardComponent,
    InfiniteScrollModule,
    HasRoleDirective
  ],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css',
})
export class NavbarComponent implements OnInit {
  isAdmin: boolean = false;
  isLogged: boolean = true;
  mainPhoto: Photo | null = null;
  username: string = '';

  notifications = {
    list: [],
    totalCount: 0,
  } as PaginationList<NotificationModel>;
  notificationPageNum: number = 1;
  constructor(
    public accountService: AccountService,
    public cartService: CartService,
    public notificationService: NotificationService
  ) {}
  ngOnInit(): void {
    this.accountService.currentUser$.subscribe((user) => {
      if (user) {
        this.cartService.getCart().subscribe();
        this.getUser(user.username);
      }
    });
    this.getUserNotifications();
  }

  logout() {
    this.accountService.logout();
  }

  getUser(username: string) {
    this.accountService.getUserData(username).subscribe((user) => {
      this.mainPhoto = user.main_photo;
      this.username = user.username;
      console.log(username);
      
    });
  }

  getUserNotifications() {
    this.notificationService
      .getNotifications(this.notificationPageNum, 3)
      .subscribe((res) => (this.notifications = res));
  }

  onScrollDown() {
    this.notificationService
      .getNotifications(++this.notificationPageNum, 3)
      .subscribe((res) => {
        let unreaded = this.notifications.list.filter(
          (n) => !n.read_at && n.isMy
        );

        for (let i = 0; i < unreaded.length; i++) {
          this.notificationService
            .makeReaded(unreaded[i].id)
            .subscribe((res) => {
              unreaded[i]!.read_at = new Date(Date.now());
            });
        }
        this.notifications.list = [...this.notifications.list, ...res.list];
        this.notifications.totalCount += res.totalCount;
      });
  }

  onScrollUp() {}
}

<nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container-fluid ">
        <a [routerLink]="['/']" class="navbar-brand">
            <i class="bi bi-shop-window fs-4"></i>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03"
            aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="navbarsExample03">
            <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                <li class="nav-item">
                    <a class="nav-link " aria-current="page" [routerLink]="['/']" routerLinkActive="active">
                        Home
                    </a>
                </li>

                <li class="nav-item" *ngIf="!(accountService.currentUser$|async)">
                    <a class="nav-link " aria-current="page" [routerLink]="['/sign-in']"
                        routerLinkActive="router-link-active">
                        Sign-In
                    </a>
                </li>



                <!-- <li class="nav-item" *ngIf="isAdmin">
                    <a [routerLink]="['/admin']" routerLinkActive="router-link-active" class="nav-link">
                        Admin
                    </a>
                </li> -->

                <li class="nav-item">
                    <a [routerLink]="['/products']" routerLinkActive="router-link-active" class="nav-link"
                        aria-disabled="true">
                        Products
                    </a>
                </li>

                <li *appHasRole="['admin']" class="nav-item">
                    <a [routerLink]="['/admin']" routerLinkActive="router-link-active" class="nav-link"
                        aria-disabled="true">
                        Admin
                    </a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a [routerLink]="'/profile/'+ username" [queryParams]="{tab:'activity'}"
                                routerLinkActive="router-link-active" class="dropdown-item">
                                Orders
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">
                                Another action
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">
                                Something else here
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>

            <i placement="bottom-right" popoverClass="rounded-1" [ngbPopover]="popContent"
                class="bi bi-bell text-white fs-5 m-2 position-relative">
                <span
                    class="position-absolute top-0 start-100 translate-middle badge rounded-pill text-bg-secondary cart-num">{{notifications.totalCount}}
                </span>
            </i>


            <ng-template #popContent>
                <div class="notify-box" (scrolled)="onScrollDown()" (scrolledUp)="onScrollUp()" infiniteScroll
                    [scrollWindow]="false" style="max-height: 350px; overflow-y:auto;">
                    <span *ngIf="notifications.list.length === 0" class="fw-bold fs-4 text-danger">Empty</span>
                    <app-notification-card *ngFor="let n of notifications.list; let index = index"
                        [notification]="n"></app-notification-card>
                </div>
            </ng-template>

            <div style="display: flex; align-items: center;" *ngIf="accountService.currentUser$|async">
                <div ngbDropdown class="d-inline-block">
                    <a routerLinkActive="router-link-active" class="nav-link">
                        <!-- <i class="text-white bi bi-person fs-5"></i> -->
                        <img ngbDropdownToggle style="height: 23px; border: 2px solid white; margin: 5px;"
                            [src]="mainPhoto?mainPhoto.url:'assets/user-placeholder.png'" />
                    </a>
                    <div ngbDropdownMenu aria-labelledby="dropdownBasic1">
                        <button ngbDropdownItem [routerLink]="['/profile/' + username ]">My Profile</button>
                        <button ngbDropdownItem class="text-danger" (click)="logout()">Logout<i
                                class="bi bi-box-arrow-left"></i></button>
                    </div>
                </div>

                <!-- <a class="text-white"  (click)="logout()">
                    <i class="bi bi-box-arrow-right fs-5" ></i>
                </a> -->

                <a style="margin-left: 3px;" [routerLink]="['/cart']" routerLinkActive="router-link-active">
                    <i class="bi bi-cart  fs-5 position-relative text-white m-2">
                        <span
                            class="position-absolute top-0 start-100 translate-middle badge rounded-pill text-bg-secondary cart-num">{{cartService.cartQuantity$|async}}</span>
                    </i>
                </a>
            </div>
            <!-- <form role="search">
                <input class="form-control " type="search" placeholder="Search" aria-label="Search" />
            </form> -->
        </div>


    </div>
</nav>

// shop/Client-Product/client/src/Components/Navbar/Navbar.jsx
import React from "react";
import { useDispatch, useSelector } from "react-redux";
import { Link, NavLink } from "react-router-dom";
import { UseDispatch } from "react-redux";
import { logout, logoutFetch, setUsers } from "../../Store/AuthReducer";
import Cart from "../Cart/Cart";
import { clearCart } from "../../Store/Reducer";
import Admin from "../AdminPanel/AdminPanel";
import { useEffect } from "react";
import { createRefresh } from "../../Store/AuthReducer";
import { environment } from "../../environment";

function Navbar() {
  const dispatch = useDispatch();
  const isLogged = useSelector((state) => state.auth.isLoggedIn);

  const isAdmin = useSelector((state) => state.auth.isAdmin);
  useEffect(() => {
    dispatch(createRefresh());
    window.addEventListener("storage", (e) => {
      //2

      if (e.storageArea == localStorage) {


        if (localStorage.getItem("logout")) {

          dispatch(logoutFetch());
          dispatch(setUsers([]));
          dispatch(clearCart());
        }
      }
    });
  }, []);
  
  const logoutClick = () => {
    //1
    localStorage.setItem("logout", ",");
    dispatch(logoutFetch());
    dispatch(setUsers([]));
    dispatch(clearCart());
    setTimeout(() => {
      localStorage.removeItem("logout");
    }, 1000);
  };

  const cartLength = useSelector((state) => state.product.cart).length;

  const cartNums = () => {
    let cartArr = Array.from(cartLength.toString());
    return cartArr.map((num) => <i className={`bi bi-${num}-square fs-6`}></i>);
  };



  const admin = isAdmin ? (
    <li className="nav-item">
      <NavLink to="/admin" className="nav-link">
        Admin
      </NavLink>
    </li>
  ) : (
    ""
  );

  return (
    <nav
      className="navbar navbar-expand-sm navbar-dark bg-dark fw-medium"
      aria-label="Third navbar example"
    >
      <div className="container-fluid ">
        <Link className="navbar-brand" to="/">
          <i class="bi bi-shop-window fs-4"></i>
        </Link>
        <button
          className="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarsExample03"
          aria-controls="navbarsExample03"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span className="navbar-toggler-icon"></span>
        </button>

        <div className="collapse navbar-collapse " id="navbarsExample03">
          <ul className="navbar-nav me-auto mb-2 mb-sm-0">
            <li className="nav-item">
              <a className="nav-link active" aria-current="page" href="#">
                Home
              </a>
            </li>

            {admin}

            <li className="nav-item">
              <NavLink
                to={"/products"}
                className="nav-link"
                aria-disabled="true"
              >
                Products
              </NavLink>
            </li>

            <li className="nav-item dropdown">
              <a
                className="nav-link dropdown-toggle"
                href="#"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Dropdown
              </a>
              <ul className="dropdown-menu">
                <li>
                  <Link className="dropdown-item" to={"/orders"}>
                    Orders
                  </Link>
                </li>
                <li>
                  <a className="dropdown-item" href="#">
                    Another action
                  </a>
                </li>
                <li>
                  <a className="dropdown-item" href="#">
                    Something else here
                  </a>
                </li>
              </ul>
            </li>
          </ul>

          <div style={{ display: "flex", alignItems: "center" }}>
            <NavLink to={"/userPage"}>
              <i
                class="bi bi-person fs-4"
                style={isLogged ? { color: "white" } : { display: "none" }}
              ></i>
            </NavLink>

            <button
              style={isLogged ? {} : { display: "none" }}
              className="btn btn-dark fs-5 "
              onClick={logoutClick}
            >
              <i class="bi bi-box-arrow-right"></i>
            </button>

            <NavLink to={"/cart"} style={{ display: environment.accessToken? "block":"none" }}>
              <i class="bi bi-cart m-3 fs-5" style={{ color: "white" }}>
                {cartNums()}
              </i>
            </NavLink>
          </div>
          <form role="search">
            <input
              className="form-control "
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
          </form>
        </div>
      </div>
    </nav>
  );
}

export default Navbar;
